insert into Category (category_id, category_name, category_type) values (1, 'Zoombeat', 'Tofu - Soft');
insert into Category (category_id, category_name, category_type) values (2, 'Lazz', 'Veal - Brisket, Provimi, Bone - In');
insert into Category (category_id, category_name, category_type) values (3, 'Livepath', 'Flour - Masa De Harina Mexican');
insert into Category (category_id, category_name, category_type) values (4, 'Meejo', 'Sprouts - Onion');
insert into Category (category_id, category_name, category_type) values (5, 'Realcube', 'Beans - Butter Lrg Lima');
insert into Category (category_id, category_name, category_type) values (6, 'Realbridge', 'Juice - Orange, 341 Ml');
insert into Category (category_id, category_name, category_type) values (7, 'Kwilith', 'Compound - Strawberry');
insert into Category (category_id, category_name, category_type) values (8, 'Yodel', 'Triple Sec - Mcguinness');
insert into Category (category_id, category_name, category_type) values (9, 'Jayo', 'Beef - Ox Tongue');
insert into Category (category_id, category_name, category_type) values (10, 'Youfeed', 'Wine - Ej Gallo Sonoma');
insert into Category (category_id, category_name, category_type) values (11, 'Divavu', 'Bagelers');
insert into Category (category_id, category_name, category_type) values (12, 'Blognation', 'Cup Translucent 9 Oz');
insert into Category (category_id, category_name, category_type) values (13, 'Lazz', 'Salmon Steak - Cohoe 8 Oz');
insert into Category (category_id, category_name, category_type) values (14, 'Quire', 'Squash - Acorn');
insert into Category (category_id, category_name, category_type) values (15, 'Yakijo', 'Fruit Salad Deluxe');
insert into Category (category_id, category_name, category_type) values (16, 'Wikido', 'Apples - Spartan');
insert into Category (category_id, category_name, category_type) values (17, 'Agimba', 'Grand Marnier');
insert into Category (category_id, category_name, category_type) values (18, 'Edgeclub', 'Energy Drink - Franks Original');
insert into Category (category_id, category_name, category_type) values (19, 'Oyoloo', 'Soup - Beef Conomme, Dry');
insert into Category (category_id, category_name, category_type) values (20, 'Fiveclub', 'Flax Seed');
insert into Category (category_id, category_name, category_type) values (21, 'Lazz', 'Soho Lychee Liqueur');
insert into Category (category_id, category_name, category_type) values (22, 'Flashpoint', 'Bread - Bistro Sour');
insert into Category (category_id, category_name, category_type) values (23, 'Dabtype', 'Sauce - Cranberry');
insert into Category (category_id, category_name, category_type) values (24, 'Yacero', 'Apple - Granny Smith');
insert into Category (category_id, category_name, category_type) values (25, 'Avamm', 'Bacardi Limon');
insert into Category (category_id, category_name, category_type) values (26, 'Izio', 'Icecream - Dibs');
insert into Category (category_id, category_name, category_type) values (27, 'Agivu', 'Nantucket - Pomegranate Pear');
insert into Category (category_id, category_name, category_type) values (28, 'Podcat', 'Rum - Mount Gay Eclipes');
insert into Category (category_id, category_name, category_type) values (29, 'Linktype', 'Langers - Ruby Red Grapfruit');
insert into Category (category_id, category_name, category_type) values (30, 'Kare', 'Alize Sunset');
insert into Category (category_id, category_name, category_type) values (31, 'Ainyx', 'Pork - Bones');
insert into Category (category_id, category_name, category_type) values (32, 'Gigabox', 'Kirsch - Schloss');
insert into Category (category_id, category_name, category_type) values (33, 'Jabberbean', 'Versatainer Nc - 9388');
insert into Category (category_id, category_name, category_type) values (34, 'Lazz', 'Jam - Blackberry, 20 Ml Jar');
insert into Category (category_id, category_name, category_type) values (35, 'Realfire', 'Muffin - Mix - Strawberry Rhubarb');
insert into Category (category_id, category_name, category_type) values (36, 'Nlounge', 'Venison - Liver');
insert into Category (category_id, category_name, category_type) values (37, 'Buzzbean', 'Foil - 4oz Custard Cup');
insert into Category (category_id, category_name, category_type) values (38, 'Babbleopia', 'Paper - Brown Paper Mini Cups');
insert into Category (category_id, category_name, category_type) values (39, 'Brainsphere', 'Veal - Round, Eye Of');
insert into Category (category_id, category_name, category_type) values (40, 'Pixoboo', 'Milk - 1%');
insert into Category (category_id, category_name, category_type) values (41, 'Plajo', 'Okra');
insert into Category (category_id, category_name, category_type) values (42, 'Zoombeat', 'Doilies - 7, Paper');
insert into Category (category_id, category_name, category_type) values (43, 'Flipbug', 'Pan Grease');
insert into Category (category_id, category_name, category_type) values (44, 'Voolia', 'Eggwhite Frozen');
insert into Category (category_id, category_name, category_type) values (45, 'Topicware', 'Cheese - Boursin, Garlic / Herbs');
insert into Category (category_id, category_name, category_type) values (46, 'Cogibox', 'Lambcasing');
insert into Category (category_id, category_name, category_type) values (47, 'Fatz', 'Onions - Red');
insert into Category (category_id, category_name, category_type) values (48, 'Meetz', 'Prunes - Pitted');
insert into Category (category_id, category_name, category_type) values (49, 'Gevee', 'Potatoes - Idaho 80 Count');
insert into Category (category_id, category_name, category_type) values (50, 'Dynava', 'Coffee Cup 16oz Foam');
insert into Category (category_id, category_name, category_type) values (51, 'Feedbug', 'Capon - Breast, Double, Wing On');
insert into Category (category_id, category_name, category_type) values (52, 'Meembee', 'Eel - Smoked');
insert into Category (category_id, category_name, category_type) values (53, 'Browsetype', 'Creme De Cacao Mcguines');
insert into Category (category_id, category_name, category_type) values (54, 'Kaymbo', 'Pastry - Raisin Muffin - Mini');
insert into Category (category_id, category_name, category_type) values (55, 'Meedoo', 'Salt - Kosher');
insert into Category (category_id, category_name, category_type) values (56, 'Ntags', 'Beans - Butter Lrg Lima');
insert into Category (category_id, category_name, category_type) values (57, 'Yotz', 'Syrup - Monin, Swiss Choclate');
insert into Category (category_id, category_name, category_type) values (58, 'Twinder', 'Tea - Herbal I Love Lemon');
insert into Category (category_id, category_name, category_type) values (59, 'Realbuzz', 'Wine - Conde De Valdemar');
insert into Category (category_id, category_name, category_type) values (60, 'Innojam', 'Duck - Whole');
insert into Category (category_id, category_name, category_type) values (61, 'Jabbersphere', 'Wine - Two Oceans Cabernet');
insert into Category (category_id, category_name, category_type) values (62, 'Realcube', 'Pork - Hock And Feet Attached');
insert into Category (category_id, category_name, category_type) values (63, 'Blogtag', 'Island Oasis - Mango Daiquiri');
insert into Category (category_id, category_name, category_type) values (64, 'Skidoo', 'Beans - Navy, Dry');
insert into Category (category_id, category_name, category_type) values (65, 'Vinte', 'Loquat');
insert into Category (category_id, category_name, category_type) values (66, 'Centimia', 'Lemons');
insert into Category (category_id, category_name, category_type) values (67, 'Tazz', 'Water - Perrier');
insert into Category (category_id, category_name, category_type) values (68, 'Mydeo', 'Soup - Canadian Pea, Dry Mix');
insert into Category (category_id, category_name, category_type) values (69, 'Realbridge', 'Table Cloth 90x90 Colour');
insert into Category (category_id, category_name, category_type) values (70, 'Yacero', 'Pasta - Gnocchi, Potato');
insert into Category (category_id, category_name, category_type) values (71, 'Mybuzz', 'Muffin Orange Individual');
insert into Category (category_id, category_name, category_type) values (72, 'Quatz', 'Vector Energy Bar');
insert into Category (category_id, category_name, category_type) values (73, 'Camido', 'Vermacelli - Sprinkles, Assorted');
insert into Category (category_id, category_name, category_type) values (74, 'Zoozzy', 'Brandy Apricot');
insert into Category (category_id, category_name, category_type) values (75, 'Blogtag', 'Cheese - Brick With Onion');
insert into Category (category_id, category_name, category_type) values (76, 'Zoomzone', 'Liqueur - Melon');
insert into Category (category_id, category_name, category_type) values (77, 'Skimia', 'Straws - Cocktale');
insert into Category (category_id, category_name, category_type) values (78, 'Divape', 'Beef - Inside Round');
insert into Category (category_id, category_name, category_type) values (79, 'Rhynyx', 'Flour - Buckwheat, Dark');
insert into Category (category_id, category_name, category_type) values (80, 'Jabbertype', 'Potatoes - Yukon Gold, 80 Ct');
insert into Category (category_id, category_name, category_type) values (81, 'Skimia', 'Celery');
insert into Category (category_id, category_name, category_type) values (82, 'Kayveo', 'Duck - Legs');
insert into Category (category_id, category_name, category_type) values (83, 'Innotype', 'Towel - Roll White');
insert into Category (category_id, category_name, category_type) values (84, 'Skipfire', 'Wine - Sherry Dry Sack, William');
insert into Category (category_id, category_name, category_type) values (85, 'Meeveo', 'Cake - Sheet Strawberry');
insert into Category (category_id, category_name, category_type) values (86, 'Zoomcast', 'Syrup - Chocolate');
insert into Category (category_id, category_name, category_type) values (87, 'Livepath', 'Pumpkin');
insert into Category (category_id, category_name, category_type) values (88, 'Tagtune', 'Soup - Knorr, Chicken Gumbo');
insert into Category (category_id, category_name, category_type) values (89, 'Fliptune', 'Cake - Pancake');
insert into Category (category_id, category_name, category_type) values (90, 'Trudeo', 'Veal - Knuckle');
insert into Category (category_id, category_name, category_type) values (91, 'Zooveo', 'Vinegar - White');
insert into Category (category_id, category_name, category_type) values (92, 'Meemm', 'Syrup - Monin, Amaretta');
insert into Category (category_id, category_name, category_type) values (93, 'Mynte', 'Rice Pilaf, Dry,package');
insert into Category (category_id, category_name, category_type) values (94, 'Bluezoom', 'Pasta - Canelloni');
insert into Category (category_id, category_name, category_type) values (95, 'Bubblebox', 'Ecolab - Lime - A - Way 4/4 L');
insert into Category (category_id, category_name, category_type) values (96, 'Youopia', 'Wine - Sherry Dry Sack, William');
insert into Category (category_id, category_name, category_type) values (97, 'Kanoodle', 'Skewers - Bamboo');
insert into Category (category_id, category_name, category_type) values (98, 'Lajo', 'Juice - Orange 1.89l');
insert into Category (category_id, category_name, category_type) values (99, 'Eimbee', 'Chicken - Wings, Tip Off');
insert into Category (category_id, category_name, category_type) values (100, 'Ailane', 'Flour - All Purpose');
