insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (1, 'mastercard', 'Citigroup Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (2, 'bankcard', 'US Ecology, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (3, 'jcb', 'Enstar Group Limited');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (4, 'mastercard', 'iShares MSCI All Country Asia ex Japan Index Fund');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (5, 'jcb', 'KMG Chemicals, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (6, 'switch', 'First Trust Taiwan AlphaDEX Fund');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (7, 'jcb', 'Open Text Corporation');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (8, 'jcb', 'Nuveen AMT-Free Quality Municipal Income Fund');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (9, 'maestro', 'Vmware, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (10, 'jcb', 'Iconix Brand Group, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (11, 'mastercard', 'USA Technologies, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (12, 'diners-club-enroute', 'SigmaTron International, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (13, 'switch', 'SEACOR Marine Holdings Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (14, 'jcb', 'Capitala Finance Corp.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (15, 'jcb', 'AgroFresh Solutions, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (16, 'mastercard', 'Organovo Holdings, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (17, 'diners-club-carte-blanche', 'The Providence Service Corporation');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (18, 'jcb', 'Nuveen Georgia Quality Municipal Income Fund ');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (19, 'jcb', 'RPC, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (20, 'china-unionpay', 'Bed Bath & Beyond Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (21, 'jcb', 'FlexShares Credit-Scored US Corporate Bond Index Fund');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (22, 'jcb', 'Baidu, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (23, 'americanexpress', 'Viper Energy Partners LP');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (24, 'jcb', 'Nokia Corporation');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (25, 'china-unionpay', 'Colony NorthStar, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (26, 'diners-club-enroute', 'Solar Capital Ltd.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (27, 'china-unionpay', 'First Trust Rising Dividend Achievers ETF');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (28, 'visa-electron', 'BLDRS Asia 50 ADR Index Fund');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (29, 'jcb', 'Santander Holdings USA, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (30, 'jcb', 'Adtalem Global Education Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (31, 'switch', 'iShares FTSE EPRA/NAREIT Europe Index Fund');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (32, 'jcb', 'Reinsurance Group of America, Incorporated');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (33, 'maestro', 'Glacier Bancorp, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (34, 'jcb', 'CatchMark Timber Trust, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (35, 'mastercard', 'Niagara Mohawk Holdings, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (36, 'jcb', 'Atlantic Coast Financial Corporation');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (37, 'mastercard', 'OpGen, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (38, 'bankcard', 'Kura Oncology, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (39, 'laser', 'Alcoa Corporation');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (40, 'laser', 'Twin Disc, Incorporated');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (41, 'jcb', 'Ladder Capital Corp');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (42, 'laser', 'BancorpSouth, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (43, 'jcb', 'Martin Marietta Materials, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (44, 'jcb', 'FutureFuel Corp.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (45, 'jcb', 'Almost Family Inc');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (46, 'mastercard', 'Southern California Edison Company');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (47, 'diners-club-us-ca', 'National General Holdings Corp');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (48, 'americanexpress', 'Forum Energy Technologies, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (49, 'jcb', 'Blackrock MuniHoldings Quality Fund, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (50, 'diners-club-enroute', 'CPFL Energia S.A.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (51, 'jcb', 'Eros International PLC');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (52, 'jcb', 'Yum! Brands, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (53, 'mastercard', 'Avon Products, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (54, 'jcb', 'Hovnanian Enterprises Inc');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (55, 'maestro', 'Magic Software Enterprises Ltd.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (56, 'maestro', 'KraneShares CSI China Internet ETF');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (57, 'jcb', 'ZAIS Group Holdings, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (58, 'jcb', 'Blackrock MuniYield Investment Fund');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (59, 'switch', 'Titan Pharmaceuticals, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (60, 'maestro', 'Interpublic Group of Companies, Inc. (The)');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (61, 'diners-club-carte-blanche', 'Accelerate Diagnostics, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (62, 'jcb', 'First Bancorp, Inc (ME)');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (63, 'americanexpress', 'Quest Diagnostics Incorporated');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (64, 'mastercard', 'Innospec Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (65, 'china-unionpay', 'Dover Corporation');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (66, 'jcb', 'Nuveen Mortgage Opportunity Term Fund');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (67, 'china-unionpay', 'CVR Energy Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (68, 'mastercard', 'Origo Acquisition Corporation');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (69, 'switch', 'Foresight Autonomous Holdings Ltd.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (70, 'jcb', 'MFA Financial, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (71, 'diners-club-us-ca', 'RenaissanceRe Holdings Ltd.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (72, 'jcb', 'ViewRay, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (73, 'china-unionpay', 'Orion Engineered Carbons S.A');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (74, 'jcb', 'Equus Total Return, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (75, 'mastercard', 'Helix Energy Solutions Group, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (76, 'mastercard', 'H&R Block, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (77, 'jcb', 'EOG Resources, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (78, 'maestro', 'BioShares Biotechnology Clinical Trials Fund');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (79, 'maestro', 'John B. Sanfilippo & Son, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (80, 'switch', 'RPC, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (81, 'americanexpress', 'Steel Partners Holdings LP');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (82, 'switch', 'Norwegian Cruise Line Holdings Ltd.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (83, 'jcb', 'CPS Technologies Corp.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (84, 'diners-club-enroute', 'Heartland Financial USA, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (85, 'jcb', 'Value Line, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (86, 'jcb', 'KKR & Co. L.P.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (87, 'china-unionpay', 'McGrath RentCorp');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (88, 'bankcard', 'Tortoise Power and Energy Infrastructure Fund, Inc');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (89, 'mastercard', 'Graphic Packaging Holding Company');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (90, 'visa-electron', 'Matlin & Partners Acquisition Corporation');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (91, 'diners-club-us-ca', 'Camden Property Trust');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (92, 'switch', 'Royal Bank Of Canada');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (93, 'solo', 'First Potomac Realty Trust');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (94, 'china-unionpay', 'Clean Diesel Technologies, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (95, 'bankcard', 'SilverSun Technologies, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (96, 'jcb', 'Applied Industrial Technologies, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (97, 'jcb', 'Aegon NV');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (98, 'jcb', 'Nexeo Solutions, Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (99, 'visa', 'YY Inc.');
insert into PaymentMethod (payment_method_id, payment_method_name, payment_gateway) values (100, 'visa', 'LM Funding America, Inc.');
